Repository codecentric-oss/niceml, pull requests merged in 2023-08, with the labels that each got.

#57 Set maximum version of pydantic to <2.0
  poetry.lock
  pyproject.toml
Labels: 🪲 bug, 🔒 security

#58 Add feature request issue template
  .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
Labels: 📋 needs review

#60 Update tensorflow to 2.12.x and dagster to 1.4.x
  configs/ops/train/op_train_objdet.yaml
  configs/ops/train/op_train_semseg.yaml
  niceml/cli/clicommands.py
  niceml/data/datadescriptions/regdatadescription.py
  poetry.lock
  pyproject.toml
  template/configs/ops/train/op_train_objdet.yaml
  template/pyproject.toml.jinja
Labels: 🪲 bug, 🔧 enhancement, 🚨 high priority, 🔒 security, ♻️ refactoring

#63 Feature/join location with path objects
  niceml/utilities/fsspec/locationutils.py
  tests/unit/niceml/utilities/test_locationutils.py
Labels: 🔧 enhancement

#56 Some improvements for `DfDataset` and working with structured data
  Makefile
  configs/jobs/job_data_generation/job_data_generation.yaml
  configs/jobs/job_eval/job_eval_reg/job_eval_reg_number.yaml
  configs/jobs/job_eval/job_eval_reg/job_eval_reg_sinus.yaml
  configs/jobs/job_train/job_train_reg/job_train_reg_number.yaml
  configs/jobs/job_train/job_train_reg/job_train_reg_sinus.yaml
  configs/ops/analysis/op_analysis_reg.yaml
  configs/ops/normalization/op_norm_numbers_tabular_data.yaml
  configs/ops/prediction/op_prediction_reg.yaml
  configs/ops/train/op_train_reg.yaml
  configs/shared/datasets/dataset_reg_sinus_test.yaml
  configs/shared/datasets/dataset_reg_test.yaml
  niceml/dagster/jobs/jobs.py
  niceml/dagster/ops/dfnormalization.py
  niceml/dagster/ops/imagetotable.py
  niceml/data/datadescriptions/regdatadescription.py
  niceml/data/dataloaders/dfloaders.py
  niceml/data/datasets/dfdataset.py
  niceml/data/datasets/healthdataset.py
  niceml/data/datasets/sinusdataset.py
  niceml/data/featurecombiners/__init__.py
  niceml/data/featurecombiners/featurecombiner.py
  niceml/data/normalization/dataframe.py
  niceml/data/normalization/minmax.py
  niceml/data/normalization/normalization.py
  niceml/dlframeworks/tensorflow/callbacks/csvlogger.py
  niceml/experiments/expfilenames.py
  niceml/experiments/schemas/defaultexpschema.py
  niceml/experiments/schemas/expmember.py
  niceml/experiments/schemas/sampleexpschemas.py
  niceml/experiments/schemas/schemalist.py
  niceml/mlcomponents/resultanalyzers/dataframes/dfanalyzer.py
  niceml/mlcomponents/resultanalyzers/tensors/tensorgraphanalyzer.py
  niceml/utilities/imagegeneration.py
  niceml/utilities/sinusgeneration.py
  template/configs/jobs/job_eval/job_eval_reg/job_eval_reg_sinus.yaml
  template/configs/jobs/job_train/job_train_reg/job_train_reg_sinus.yaml
  template/configs/shared/datasets/dataset_reg_sinus_test.yaml
  tests/configs/test_configs_instantiate.py
  tests/end_to_end/conftest.py
  tests/end_to_end/pipelines/test_eval.py
  tests/end_to_end/pipelines/test_train.py
  tests/unit/niceml/data/normalization/test_dataframe.py
  tests/unit/niceml/data/normalization/test_minmax.py
  tests/unit/niceml/mkdocs/test_schemadocgeneration.py
  tests/unit/niceml/utilities/test_hydrautils.py
  tests/unit/niceml/utilities/test_imagegeneration.py
  tests/unit/niceml/utilities/test_sinusgeneration.py
Labels: 🪲 bug, ✨ feature, ⚡️ performance, 📋 needs review, 🌀 cleanup, ♻️ refactoring

#69 fix: remove tensorflow-io-gcs-filesystem from dependencies
  copier.yaml
  poetry.lock
  pyproject.toml
Labels: 🪲 bug, 🚨 high priority

#71 fix: implemented image_size.from_pil image and size
  niceml/utilities/imagesize.py
  tests/unit/niceml/utilities/test_imagesize.py
Labels: ✨ feature
