Repository codecentric-oss/niceml, pull requests merged in 2023-05, with the labels that each got.

#8 Fix release workflow
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
  .pre-commit-config.yaml
  niceml/__init__.py
  poetry.lock
  pyproject.toml
Labels: bug

#9 Fix release pipeline
  .github/workflows/docs.yaml
  .github/workflows/pytest.yaml
  .github/workflows/release.yaml
  .isort.cfg
  poetry.lock
  pyproject.toml
  setup.cfg
  tests/end_to_end/pipelines/test_eval.py
  tests/end_to_end/pipelines/test_train.py
Labels: bug

#10 Fix ref attribute of action/checkout
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
Labels: bug

#13 feat: Add `niceml init` as cli command to initialize a new niceml project
  .isort.cfg
  README.md
  copier.yaml
  niceml/cli/clicommands.py
  niceml/cli/climain.py
  niceml/py.typed
  poetry.lock
  pyproject.toml
  setup.cfg
  template/.env
  template/.pre-commit-config.yaml
  template/README.md.jinja
  template/configs/dashboard/local.yaml
  template/configs/dashboard/local_minio.yaml
  template/configs/jobs/job_data_generation/job_data_generation.yaml
  template/configs/jobs/job_eval/job_eval_objdet/job_eval_objdet_number.yaml
  template/configs/jobs/job_eval/job_eval_reg/job_eval_reg_sinus.yaml
  template/configs/jobs/job_train/job_train_cls/job_train_cls_binary.yaml
  template/configs/jobs/job_train/job_train_cls/job_train_cls_multitarget.yaml
  template/configs/jobs/job_train/job_train_cls/job_train_cls_softmax.yaml
  template/configs/jobs/job_train/job_train_objdet/job_train_objdet_number.yaml
  template/configs/jobs/job_train/job_train_reg/job_train_reg_sinus.yaml
  template/configs/jobs/job_train/job_train_semseg/job_train_semseg_number.yaml
  template/configs/ops/analysis/op_analysis_cls_binary.yaml
  template/configs/ops/analysis/op_analysis_cls_multitarget.yaml
  template/configs/ops/analysis/op_analysis_cls_softmax.yaml
  template/configs/ops/analysis/op_analysis_objdet.yaml
  template/configs/ops/analysis/op_analysis_semseg.yaml
  template/configs/ops/crop_numbers/op_crop_numbers.yaml
  template/configs/ops/data_generation/op_data_generation_number.yaml
  template/configs/ops/experiment/op_experiment_default.yaml
  template/configs/ops/exptests/exptests_default.yaml
  template/configs/ops/prediction/datasets/datasets_generic_default.yaml
  template/configs/ops/prediction/op_prediction_base.yaml
  template/configs/ops/prediction/op_prediction_cls.yaml
  template/configs/ops/prediction/op_prediction_objdet.yaml
  template/configs/ops/prediction/op_prediction_semseg.yaml
  template/configs/ops/prediction/prediction_handler/prediction_handler_objdet.yaml
  template/configs/ops/prediction/prediction_handler/prediction_handler_semseg.yaml
  template/configs/ops/prediction/prediction_handler/prediction_handler_vector.yaml
  template/configs/ops/split_data/op_split_data_number.yaml
  template/configs/ops/train/callbacks/callbacks_base.yaml
  template/configs/ops/train/exp_initializer/exp_initializer_default.yaml
  template/configs/ops/train/op_train_base.yaml
  template/configs/ops/train/op_train_cls_binary.yaml
  template/configs/ops/train/op_train_objdet.yaml
  template/configs/ops/train/op_train_semseg.yaml
  template/configs/ops/train/train_params/trainparams_default.yaml
  template/configs/shared/credentials/credentials_minio.yaml
  template/configs/shared/datasets/dataset_cls_test.yaml
  template/configs/shared/datasets/dataset_objdet_test.yaml
  template/configs/shared/datasets/dataset_reg_sinus_test.yaml
  template/configs/shared/datasets/dataset_semseg_test.yaml
  template/configs/shared/locations/exp_locations.yaml
  template/pyproject.toml.jinja
  template/{{_copier_conf.answers_file}}.jinja
  template/{{package_name}}/__init__.py
Labels: enhancement

#17 Fix classifiers
  pyproject.toml
Labels: bug

#18 Fix project meta
  pyproject.toml
Labels: bug

#19 Set commit_version_number to true
  .github/workflows/release.yaml
  pyproject.toml
Labels: bug

#20 Feature/add dagit
  configs/dashboard/local.yaml
  configs/dashboard/local_minio.yaml
  configs/jobs/job_train/job_train_semseg/job_train_semseg_number.yaml
  configs/shared/locations/exp_locations.yaml
  niceml/cli/clicommands.py
  niceml/experiments/experimentmanager.py
  poetry.lock
  pyproject.toml
  sample.env
  template/.env
  template/configs/dashboard/local.yaml
  template/configs/dashboard/local_minio.yaml
  template/configs/shared/locations/exp_locations.yaml
Labels: bug, enhancement

#21 Expand numbers dataset with tabular data
  configs/jobs/job_data_generation/job_data_generation.yaml
  configs/ops/image_to_tabular_data/op_image_to_tabular_data.yaml
  niceml/dagster/jobs/jobs.py
  niceml/dagster/ops/cropnumbers.py
  niceml/dagster/ops/imagetotable.py
  niceml/utilities/imagegeneration.py
  pyproject.toml
  tests/unit/niceml/utilities/test_imagegeneration.py
Labels: bug, enhancement

#22 Add image augmentation to the background images of the numbers dataset
  README.md
  niceml/utilities/imagegeneration.py
  poetry.lock
  pyproject.toml
  tests/unit/niceml/utilities/boundingboxes/test_bboxdrawing.py
  tests/unit/niceml/utilities/test_imagegeneration.py
Labels: enhancement

#25 Merge for release v0.3.0
  README.md
  configs/dashboard/local.yaml
  configs/dashboard/local_minio.yaml
  configs/jobs/job_data_generation/job_data_generation.yaml
  configs/jobs/job_train/job_train_semseg/job_train_semseg_number.yaml
  configs/ops/image_to_tabular_data/op_image_to_tabular_data.yaml
  configs/shared/locations/exp_locations.yaml
  docs/dashboard-experiment-type.png
  docs/dashboard.md
  docs/dashboard.png
  docs/dataframe.csv
  docs/faq.md
  docs/generate-data.md
  docs/how-to-guides.md
  docs/index.md
  docs/test-data-sample1.json
  docs/test-data-sample1.png
  docs/test-data-sample1_mask.png
  docs/test-data-sample_cropped.png
  docs/tutorials.md
  mkdocs.yaml
  niceml/cli/clicommands.py
  niceml/dagster/jobs/jobs.py
  niceml/dagster/ops/cropnumbers.py
  niceml/dagster/ops/imagetotable.py
  niceml/dashboard/components/downloadexpviscomponent.py
  niceml/experiments/experimentmanager.py
  niceml/storages/abs.py
  niceml/utilities/imagegeneration.py
  poetry.lock
  pyproject.toml
  sample.env
  template/.env
  template/configs/dashboard/local.yaml
  template/configs/dashboard/local_minio.yaml
  template/configs/shared/locations/exp_locations.yaml
  tests/unit/niceml/utilities/boundingboxes/test_bboxdrawing.py
  tests/unit/niceml/utilities/test_imagegeneration.py
Labels: bug, documentation, enhancement

#28 Remove links to subpages from index.md
  docs/index.md
Labels: bug, documentation
