Repository codecentric-oss/niceml, pull requests merged in 2023-10, with the labels that each got.

#82 fix: remove job flag to prevent multiple mlflow runs
  niceml/dagster/jobs/jobs.py
Labels: 🪲 bug

#83 Release preparation v0.8.2
  niceml/dagster/jobs/jobs.py
Labels: 🪲 bug, 🔧 enhancement

#84 fix: add installation info to main documentation
  docs/getting-started.md
  docs/index.md
Labels: 📚 documentation

#85 datasets and all components need to be pickable, and lambdas are not
  niceml/data/datainfolistings/clsdatainfolisting.py
Labels: 🪲 bug
