Repository codecentric-oss/niceml, pull requests merged in 2023-06, with the labels that each got.

#30 feat: Softmax for Semantic Segmentation
  niceml/data/datadescriptions/outputdatadescriptions.py
  niceml/data/datadescriptions/semsegdatadescritption.py
  niceml/data/netdataloggers/semsegnetdatalogger.py
  niceml/dlframeworks/tensorflow/losses/semseglosses.py
  niceml/dlframeworks/tensorflow/models/unets.py
  niceml/mlcomponents/predictionhandlers/semsegpredictionhandler.py
  niceml/scripts/hydraconfreader.py
Labels: enhancement

#34 Update the version of dagster to 1.3.9
  poetry.lock
  pyproject.toml
Labels: 🪲 bug, 🚨 high priority, 🔒 security, 📋 needs review

#43 Feat/readlock during training
  configs/jobs/job_train/job_train_objdet/job_train_objdet_number.yaml
  configs/jobs/job_train/job_train_semseg/job_train_semseg_number.yaml
  configs/shared/filelocks/op_data_readlock.yaml
  niceml/config/hydra.py
  niceml/dagster/jobs/jobs.py
  niceml/dagster/ops/analysis.py
  niceml/dagster/ops/filelockops.py
  niceml/dagster/ops/prediction.py
  niceml/dagster/ops/train.py
  niceml/mkdocs/mdop.py
  niceml/utilities/readwritelock.py
  tests/unit/niceml/utilities/test_readwritelock.py
Labels: ✨ feature

#40 Adjust project template to current feature set
  template/configs/dashboard/local.yaml
  template/configs/dashboard/local_minio.yaml
  template/configs/jobs/job_data_generation/job_data_generation.yaml
  template/configs/jobs/job_train/job_train_semseg/job_train_semseg_number.yaml
  template/configs/ops/image_to_tabular_data/op_image_to_tabular_data.yaml
  template/pyproject.toml.jinja
Labels: 🪲 bug, 📋 needs review, ⚙️ configuration

#44 Add a FileChecksumProcessor
  niceml/filechecksumprocessors/__init__.py
  niceml/filechecksumprocessors/filechecksumprocessor.py
  niceml/filechecksumprocessors/zippedcsvtoparqprocessor.py
  tests/unit/niceml/filechecksumprocessors/__init__.py
  tests/unit/niceml/filechecksumprocessors/test_filechecksumprocessor.py
  tests/unit/niceml/filechecksumprocessors/test_zippedcsvtoparqprocessor.py
Labels: ✨ feature, 📋 needs review

#45 Add file locks and `FileChecksumProcessors`
  configs/jobs/job_train/job_train_objdet/job_train_objdet_number.yaml
  configs/jobs/job_train/job_train_semseg/job_train_semseg_number.yaml
  configs/shared/filelocks/op_data_readlock.yaml
  niceml/config/hydra.py
  niceml/dagster/jobs/jobs.py
  niceml/dagster/ops/analysis.py
  niceml/dagster/ops/filelockops.py
  niceml/dagster/ops/prediction.py
  niceml/dagster/ops/train.py
  niceml/filechecksumprocessors/__init__.py
  niceml/filechecksumprocessors/filechecksumprocessor.py
  niceml/filechecksumprocessors/zippedcsvtoparqprocessor.py
  niceml/mkdocs/mdop.py
  niceml/utilities/readwritelock.py
  pyproject.toml
  tests/unit/niceml/filechecksumprocessors/__init__.py
  tests/unit/niceml/filechecksumprocessors/test_filechecksumprocessor.py
  tests/unit/niceml/filechecksumprocessors/test_zippedcsvtoparqprocessor.py
  tests/unit/niceml/utilities/test_readwritelock.py
Labels: ✨ feature
