Repository codecentric-oss/niceml, pull requests merged in 2023-09, with the labels that each got.

#72 Feature/optimize file locks
  niceml/utilities/readwritelock.py
  template/configs/ops/train/op_train_semseg.yaml
Labels: 🪲 bug, 🔧 enhancement

#70 Cleanup poetry lock
  Makefile
  copier.yaml
  docs/getting-started.md
  poetry.lock
  template/pyproject.toml.jinja
Labels: 🪲 bug, 🌀 cleanup, ♻️ refactoring

#73 Release preparation v0.7.3
  niceml/utilities/imagesize.py
  niceml/utilities/readwritelock.py
  template/configs/ops/train/op_train_semseg.yaml
  tests/unit/niceml/utilities/test_imagesize.py
Labels: 🪲 bug, 🔧 enhancement, ♻️ refactoring

#76 fix: Return the experiment path instead of the experiment
  niceml/experiments/experimenterrors.py
  niceml/experiments/exppathfinder.py
  tests/unit/niceml/experiments/test_exppathfinder.py
Labels: 🪲 bug

#78 added predictionfunction and models as folder
  configs/ops/prediction/op_prediction_base.yaml
  niceml/dagster/ops/prediction.py
  niceml/dlframeworks/tensorflow/predictionfunctions/__init__.py
  niceml/dlframeworks/tensorflow/predictionfunctions/keraspredictionfunction.py
  niceml/experiments/experimentdata.py
  niceml/mlcomponents/predictionfunction/__init__.py
  niceml/mlcomponents/predictionfunction/predictionfunction.py
Labels: ✨ feature

#77 Copy config files to the template as part of the release workflow
  .github/workflows/release.yaml
Labels: 🪲 bug, 🔧 enhancement, ⚙️ configuration

#79 Feature/mlflow integration
  .gitignore
  configs/jobs/job_eval/job_eval_objdet/job_eval_objdet_number.yaml
  configs/jobs/job_eval/job_eval_reg/job_eval_reg_number.yaml
  configs/jobs/job_train/job_train_cls/job_train_cls_binary.yaml
  configs/jobs/job_train/job_train_cls/job_train_cls_multitarget.yaml
  configs/jobs/job_train/job_train_cls/job_train_cls_softmax.yaml
  configs/jobs/job_train/job_train_objdet/job_train_objdet_number.yaml
  configs/jobs/job_train/job_train_reg/job_train_reg_number.yaml
  configs/jobs/job_train/job_train_semseg/job_train_semseg_number.yaml
  configs/resources/mlflow/res_mlflow_base.yaml
  niceml/config/defaultremoveconfigkeys.py
  niceml/config/writeopconfig.py
  niceml/dagster/jobs/jobs.py
  niceml/dagster/ops/analysis.py
  niceml/dagster/ops/experiment.py
  niceml/dagster/ops/exptests.py
  niceml/dagster/ops/prediction.py
  niceml/dagster/ops/train.py
  niceml/dlframeworks/tensorflow/learners/defaultlearner.py
  niceml/experiments/experimenttests/testinitializer.py
  niceml/mlcomponents/resultanalyzers/dataframes/dfanalyzer.py
  niceml/mlcomponents/resultanalyzers/tensors/tensorgraphanalyzer.py
  poetry.lock
  pyproject.toml
Labels: ✨ feature

#80 Release preparation v0.8.0
  .github/workflows/release.yaml
  .gitignore
  configs/jobs/job_eval/job_eval_objdet/job_eval_objdet_number.yaml
  configs/jobs/job_eval/job_eval_reg/job_eval_reg_number.yaml
  configs/jobs/job_train/job_train_cls/job_train_cls_binary.yaml
  configs/jobs/job_train/job_train_cls/job_train_cls_multitarget.yaml
  configs/jobs/job_train/job_train_cls/job_train_cls_softmax.yaml
  configs/jobs/job_train/job_train_objdet/job_train_objdet_number.yaml
  configs/jobs/job_train/job_train_reg/job_train_reg_number.yaml
  configs/jobs/job_train/job_train_semseg/job_train_semseg_number.yaml
  configs/ops/prediction/op_prediction_base.yaml
  configs/resources/mlflow/res_mlflow_base.yaml
  niceml/config/defaultremoveconfigkeys.py
  niceml/config/writeopconfig.py
  niceml/dagster/jobs/jobs.py
  niceml/dagster/ops/analysis.py
  niceml/dagster/ops/experiment.py
  niceml/dagster/ops/exptests.py
  niceml/dagster/ops/prediction.py
  niceml/dagster/ops/train.py
  niceml/dlframeworks/tensorflow/learners/defaultlearner.py
  niceml/dlframeworks/tensorflow/predictionfunctions/__init__.py
  niceml/dlframeworks/tensorflow/predictionfunctions/keraspredictionfunction.py
  niceml/experiments/experimentdata.py
  niceml/experiments/experimenterrors.py
  niceml/experiments/experimenttests/testinitializer.py
  niceml/experiments/exppathfinder.py
  niceml/mlcomponents/predictionfunction/__init__.py
  niceml/mlcomponents/predictionfunction/predictionfunction.py
  niceml/mlcomponents/resultanalyzers/dataframes/dfanalyzer.py
  niceml/mlcomponents/resultanalyzers/tensors/tensorgraphanalyzer.py
  poetry.lock
  pyproject.toml
  tests/unit/niceml/experiments/test_exppathfinder.py
Labels: 🪲 bug, ✨ feature, 🔧 enhancement, 🔒 security, ⚙️ configuration, ♻️ refactoring

#81 fix: analysis now have credentials for datasets
  niceml/dagster/jobs/jobs.py
  niceml/dagster/ops/analysis.py
  niceml/dagster/ops/experiment.py
  niceml/dagster/ops/prediction.py
Labels: 🪲 bug
