Repository codecentric-oss/niceml, pull requests merged in 2023-07, with the labels that each got.

#47 Remove temporary directory from hydra search path
  niceml/config/hydra.py
  niceml/dagster/jobs/jobs.py
Labels: 🪲 bug, 📋 needs review, ⚙️ configuration, ♻️ refactoring

#50 fix: save result files from tensorgraphanalyzer at the correct place …
  niceml/experiments/schemas/baseexpschema.py
  niceml/experiments/schemas/defaultexpschema.py
  niceml/experiments/schemas/objdetexpschema.py
  niceml/experiments/schemas/sampleexpschemas.py
  niceml/mlcomponents/resultanalyzers/tensors/tensorgraphanalyzer.py
Labels: 🪲 bug, ✅ completed, 🔧 enhancement, 🧪 testing

#48 Add dataframe normalization op
  niceml/dagster/ops/dfnormalization.py
  niceml/data/normalization/__init__.py
  niceml/data/normalization/dataframe.py
  niceml/data/normalization/normalization.py
  niceml/filechecksumprocessors/zippedcsvtoparqprocessor.py
  niceml/utilities/ioutils.py
  tests/unit/niceml/data/normalization/__init__.py
  tests/unit/niceml/data/normalization/test_dataframe.py
Labels: ✨ feature, 📋 needs review

#54 Add automatic generation of API documentation based on docstrings
  docs/SUMMARY.md
  docs/jobs/apidocs.py
  docs/jobs/jobsdoc.py
  mkdocs.yaml
  niceml/cli/__init__.py
  niceml/storages/__init__.py
  poetry.lock
  pyproject.toml
Labels: 📚 documentation, ✨ feature, 📋 needs review
