Repository codecentric-oss/niceml, pull requests merged in 2023-12, with the labels that each got.

#93 Fix/list dir filter ext
  niceml/utilities/ioutils.py
  tests/unit/niceml/utilities/test_ioutils.py
Labels: 🪲 bug, 🧪 testing

#94 feat: optimize file locks
  niceml/utilities/readwritelock.py
  tests/unit/niceml/utilities/test_readwritelock.py
Labels: 🪲 bug, ✨ feature, 🧪 testing

#102 Make `DfDataset` and `GenericDataset` abstract
  niceml/data/datasets/dfdataset.py
  niceml/data/datasets/genericdataset.py
Labels: 🪲 bug

#103 Feature/add contribution docs
  CODE_OF_CONDUCT.md
  CODING_STANDARDS.md
  COMMIT_GUIDELINES.md
  CONTRIBUTION.md
  DEV_ENV_SETUP.md
  docs/CODE_OF_CONDUCT.md
  docs/CODING_STANDARDS.md
  docs/COMMIT_GUIDELINES.md
  docs/CONTRIBUTION.md
  docs/DEV_ENV_SETUP.md
  docs/SUMMARY.md
Labels: 📚 documentation, 🔧 enhancement, ♻️ refactoring
