Repository codecentric-oss/niceml, pull requests merged in 2024-01, with the labels that each got.

#106 Feature/update tensorflow and dagster
  .github/workflows/pytest.yaml
  niceml/dlframeworks/keras/callbacks/modelcheckpoint.py
  poetry.lock
  pyproject.toml
Labels: 🔧 enhancement

#108 Set pytest workflow trigger to `pull_request_target`
  .github/workflows/pytest.yaml
  docs/getting-started.md
  poetry.lock
  pyproject.toml
Labels: 📚 documentation, ⚙️ configuration, ♻️ refactoring

#111 Set the Python version of the release workflow to 3.10
  .github/workflows/release.yaml
Labels: 🪲 bug, 🚨 high priority

#112 Set Python version to 3.11
  .github/workflows/release.yaml
Labels: 🪲 bug

#113 feat: update altair to 5.2.0
  niceml/utilities/chartutils.py
  poetry.lock
  pyproject.toml
Labels: 🎨 UI/UX
